services:
  db:
    image: postgres    
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  dbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8978:8978
  backend:
    build: 
      context: backend
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:3000"
  frontend:
    build: frontend
    environment:
      NODE_ENV: production
    ports:
      - "8001:3000"
